# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/Start/Start.cache/wt [current_project]
set_property parent.project_path D:/Vivado/Start/Start.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado/Start/Start.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/new/MeAly.coe
read_verilog -library xil_defaultlib {
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/ButtonInput.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/ClockDivider.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/Random.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/Snake.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/UpdateClock.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Snake_Dev/MealyFanClubProject-Snake_Dev/Snake/Snake.srcs/sources_1/new/VGA_ALY.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/font_rom.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/m100_counter.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/pong_graph.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/pong_text.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/pong_top.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/timer.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/new/vga_640x480.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/new/vga_stripes_top.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/vga_sync.v
  C:/Users/Willy/Desktop/MealyFanClubProject-Pong_Dev/MealyFanClubProject-Pong_Dev/Pong/Pong.srcs/sources_1/new/Game_top.v
}
read_vhdl -library xil_defaultlib C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/new/Mealy.vhd
read_ip -quiet C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/constrs_1/new/VGA.xdc
set_property used_in_implementation false [get_files C:/Users/Willy/Desktop/MealyFanClubProject-Start/MealyFanClubProject-Start/VGA.srcs/constrs_1/new/VGA.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Game_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Game_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Game_top_utilization_synth.rpt -pb Game_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
